[package]
name = 'klaudo'
version = '0.1.0'
edition = '2024'

[dependencies]
clap = { version = '4.6.7', default-features = false, features = ['std', 'derive', 'help', 'usage', 'error-context'] }
dotenvy = '0.15.7'
kuriero = { git = 'https://github.com/karin0/kuriero.git', rev = 'fe9770f84d6ab05a625660aed34578b982388b73' }
libc = '0.2.189'
serde = { version = '1.0.229', features = ['derive'] }
serde_json = '1.0.151'
ureq = { version = '3.4.2', features = ['multipart'] }

[dev-dependencies]
httparse = '1.10.1'
tempfile = '3.27.0'

[lints.rust]
warnings = 'deny'

[lints.clippy]
pedantic = { level = 'warn', priority = -1 }

[profile.release]
codegen-units = 1
lto = true
strip = true
